-- Migration number: 0003 	 2025-12-18T09:29:22.547Z
INSERT INTO Members (Alias, Twitch, Youtube, YoutubeId, DiscordInvite)
VALUES (
    'Ducked',
    'duckedgtnh',
    '@DuckedGTNH',
    'UCJfAntp9CIFvjmlXeDK7Oxg',
    'discord.gg/ufa5xm9PK7'
  ),
  (
    'Neurotic Goose',
    NULL,
    '@NeuroticGoose',
    'UCI9xZDIcR7Ei-s2g_6ru1sw',
    'discord.gg/ufa5xm9PK7'
  ),
  (
    'Hecuba',
    NULL,
    '@hecuba39',
    'UCJzyqivEVGq4NVOdpd8HLGg',
    NULL
  ),
  (
    'HamCorp (Tooj)',
    NULL,
    '@ham-corp',
    'UCNnaNSEzrD5pwDj5sKfklyQ',
    NULL
  ),
  (
    'Soycake',
    NULL,
    '@soycake',
    'UCwm_VlOAG3svWsgb_9yUU1Q',
    NULL
  ),
  (
    'Three',
    NULL,
    '@ignThree',
    'UCBls0NaDrg1wfnQBsWp9QoQ',
    NULL
  ),
  (
    'Dragonium',
    NULL,
    '@dragonium10190',
    'UCA64FHfje_BWD9CXHNmQq1A',
    NULL
  ),
  (
    'ChiefLogan',
    NULL,
    '@chieflogan_',
    'UCogZrz65kvH51R6poGP9h7w',
    NULL
  ),
  (
    'Jetlagg',
    NULL,
    '@jetlaggmc',
    'UC5kvFyjx8MLxh8UxWJ1nycg',
    NULL
  ),
  (
    'Jolliwog',
    NULL,
    '@jolliwog',
    'UCwt3BN0QhUgaaI7DmlrvOZg',
    NULL
  ),
  (
    'Sol IX',
    'sol_ix',
    '@IX_Streams',
    'UC84omxn-MQ-cgPlt_VEM8GQ',
    'discord.com/invite/mEUV7fwdfF'
  ),
  (
    'Mastiox',
    'mastiox',
    '@Mastiox',
    'UCMn7ugJXKqfj2JShiVWkiFw',
    NULL
  ),
  (
    'Flurben',
    'flurbenlive',
    '@Flurben',
    'UC-lzgxso7dUxEWKUaHQObpQ',
    NULL
  ),
  (
    'Glistew',
    'glistew',
    '@glistew',
    'UC0PVB7cejHbW5JOvmSr5SsQ',
    NULL
  ),
  (
    'Aspect',
    NULL,
    '@aspectsounds',
    'UCUjAzoOG_Z8tiN79yF6WT-g',
    NULL
  );